version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cssnano
    versions:
    - 4.1.10
    - 4.1.11
    - 5.0.0
    - 5.0.1
  - dependency-name: postcss-import
    versions:
    - 12.0.1
    - 14.0.0
  - dependency-name: postcss-cli
    versions:
    - 7.1.2
  - dependency-name: postcss-reporter
    versions:
    - 6.0.1
