permalink: pretty
highlighter: rouge
kramdown:
  input: GFM
include:
  - '_data'
exclude:
  - '.github'
  - 'CODE_OF_CONDUCT.md'
  - 'LICENSE.md'
  - 'OWNERS.md'
  - 'README.md'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'node_modules'
  - 'npm-debug.log'
  - 'package.json'
  - 'postcss.config.json'
  - 'src'
theme_color: 'blue'
